import tempfile
from typing import Optional

import numpy as np

import diplomat.processing.type_casters as tc
from diplomat.frontends import ModelInfo, ModelLike
from diplomat.utils.cli_tools import Flag
from diplomat.utils.lazy_import import resolve_lazy_imports

from .run_utils import _load_model_configs, _paths_to_str
from .sleap_imports import torch
from .sleap_providers import PredictorExtractor


def _resolve_device(gpu_index: Optional[int], use_cpu: bool) -> str:
    if use_cpu:
        return "cpu"
    if torch.cuda.is_available():
        if gpu_index is not None:
            return f"cuda:{gpu_index}"
        return "cuda"
    if torch.backends.mps.is_available():
        return "mps"
    return "cpu"


@resolve_lazy_imports
@tc.typecaster_function
def load_models(
    config: tc.Union[tc.List[tc.PathLike], tc.PathLike],
    batch_size: tc.Optional[int] = None,
    num_outputs: tc.Optional[int] = None,
    gpu_index: tc.Optional[int] = None,
    refinement_kernel_size: int = 5,
    use_cpu: Flag = False,
) -> tc.Tuple[ModelInfo, ModelLike]:
    """
    Run DIPLOMAT tracking on videos using a SLEAP trained network.

    :param config: The path or list of paths to the SLEAP model folders or config files ("training_config.yaml").
                   Can also be a zip file containing a single or multiple sleap models, in which case DIPLOMAT will
                   automatically extract models from the zip file.
    :param batch_size: The batch size to use while processing. Defaults to None, which uses the default batch size for the project.
    :param num_outputs: The number of outputs, or bodies to track in the video. Defaults to the value specified in the DLC config, or None if one
                        is not specified.
    :param gpu_index: Integer index of the GPU to use for inference (in tensorflow) defaults to 0, or selecting the first detected GPU if available.
    :param refinement_kernel_size: Size of refinement kernel used for computing offsets if an offset map is not generated by the model. Defaults to 5.
    :param use_cpu: If True, run on cpu even if a gpu is available. Defaults to False.

    :return: A model info dictionary, and a sleap model wrapper that can be used to estimate poses from video frames.
    """
    with tempfile.TemporaryDirectory() as temp_dir:
        config = _load_model_configs(_paths_to_str(config), temp_dir)
        device = _resolve_device(gpu_index, bool(use_cpu))
        provider = PredictorExtractor(config, device, refinement_kernel_size)

    meta = provider.get_metadata()

    if batch_size is None:
        batch_size = meta["batch_size"]

    return (
        ModelInfo(
            num_outputs=num_outputs,
            batch_size=batch_size,
            dotsize=int(np.ceil(meta["sigma"] / meta["input_scaling"])),
            colormap=None,
            shape_list=None,
            alphavalue=0.7,
            pcutoff=0.1,
            line_thickness=1,
            bp_names=meta["bp_names"],
            skeleton=meta["skeleton"],
            frontend="sleap",
        ),
        provider.extract,
    )
