name: Trigger Pipeline on Tag Update

on:
  push:
    tags:
      - 'v*.*.*'
  create:
    tags:
      - 'v*.*.*'


jobs:
  rebuild-and-deploy:
    uses: ./.github/workflows/publish-to-pypi.yml
    with:
      new-release-tag: ${{ github.ref_name }}
    secrets: inherit